### ISSUE TITLE
Initialise Repository

### ISSUE THREAD

**Issue by yongchenglow** [yongchenglow/livestorm-meeting-tools#1]
### Tasks

- [x] Initialise the repository with Livestorm code
- [x] Add Table of Contents to ReadMe
- [x] Add basic information about how to run
- [x] Add basic file structure
- [x] Add Acknowledgements
- [x] Add License
