### ISSUE TITLE
Create UI Designs

### ISSUE THREAD

**Issue by yongchenglow** [yongchenglow/livestorm-meeting-tools#2]
### Tasks

- [ ] Research
- [ ] Define Problem Statement
- [ ] Create User Stories
- [ ] Create Personas
- [x] Create Low Fi Prototype on Figma

**Comment by yongchenglow** [comment]
Closing this issue as the Hackathon is over will have to re-think about the future of meeting tools and how the community will continue to tackle the issue
